### ISSUE TITLE
0.2 TODO - Master List

### ISSUE THREAD

**Issue by nathwill** [nathwill/chef-systemd#1]
here we go! general idea in the organisation below is that things that are unique within a running system are handled as recipes, and if there's multiple something's, done as a resource.
- [x] units
  - [x] systemd_unit base resource
    - [x] drop-in support
  - [x] systemd_service resource
  - [x] systemd_socket resource
  - [x] systemd_mount resource
  - [x] sytemd_automount resource
  - [x] systemd_swap resource
  - [x] systemd_device resource
  - [x] systemd_path resource
  - [x] systemd_slice resource
  - [x] systemd_target resource
  - [x] systemd_timer resource
- [x] daemons
  - [x] systemd_daemon base resource
    - [x] drop-in support
  - [x] journald recipe
  - [x] logind recipe
  - [x] resolved recipe
  - [x] timesyncd recipe
- [x] utilities
  - [x] systemd_util base resource
    - [x] drop-in support
  - [x] hostnamed recipe
  - [x] journal-gatewayd recipe
  - [x] machined recipe
  - [x] networkd recipe
  - [x] timedated recipe
  - [x] bootchart
  - [x] coredump
  - [x] locale
  - [x] sleep
  - [x] sysctl
  - [x] system
  - [x] user
  - [x] tmpfiles
  - [x] udev
  - [x] vconsole
- [x] documentation (never _actually_ "done")
- [x] test-coverage (never _actually_ "done")

**Comment by mburns** [comment]
I suspect you didn't add a space between the square brackets `[]`, which Markdown fails to convert to checkboxes.

`- [ ] foo` makes:
- [ ] foo

**Comment by nathwill** [comment]
Ah, sure enough. Thanks!

**Comment by nathwill** [comment]
@ranjib @stevendanna in the spirit of releasing early and often, i'm inclined to call our progress to date sufficient for an 0.1.0 release to supermarket, and start tackling the daemon-recipes for version 0.2.0 while collecting feedback from early adopters.

thoughts?

**Comment by stevendanna** [comment]
@nathwill First, awesome work, thank you for diving into this so quickly.  Second, I totally agree.  Let's get some user feedback as soon as possible on the APIs and such since we'll have to live with them for a while.

**Comment by nathwill** [comment]
my pleasure :smile: excited to put this out there and start using it and getting some feedback. https://github.com/nathwill/chef-systemd/pull/9 is super close to finished, so as soon as we've finished cleaning it up and merged it, i'll cut and upload a release :rocket:

**Comment by nathwill** [comment]
0.1.1 shipped to supermarket! :tada:

**Comment by nathwill** [comment]
@stevendanna @ranjib well, we've got a pretty good skeleton laid out for all the basics; you guys down with shipping 0.2.0?

**Comment by nathwill** [comment]
@stevendanna @ranjib heads up, barring objections or discovery of any major issues, i'm planning to ship 0.2.0 tomorrow.

**Comment by nathwill** [comment]
https://github.com/nathwill/chef-systemd/pull/27
